httpServer {
  publicApiHttpPort = 8081
  privateApiHttpPort = 8086
  telemetry.logging.enabled = true
}

auth {
  apiKey {
    value = "MySecuredApiKey"
    value = ${?HTTP_ADVANCED_API_KEY}
  }
}

httpClient {
  dataApi {
    url = "http://localhost:8080"
    url = ${?DATA_API_URL}
    requestTimeout = 10s
  }
  telemetry.logging.enabled = true
}

logging {
  levels {
    "ROOT": "INFO"
    "ru.tinkoff.kora": "INFO"
  }
}

