httpServer {
  publicApiHttpPort = 8080
  privateApiHttpPort = 8085
  telemetry.logging.enabled = true
}

cache.caffeine.users {
  maximumSize = 1000
  expireAfterWrite = "10m"
}

cache.redis.users {
  keyPrefix = "users-"
  expireAfterWrite = "30m"
}

lettuce {
  uri = "redis://localhost:6379"
  uri = ${?REDIS_URL}
  user = ${?REDIS_USER}
  password = ${?REDIS_PASS}
  socketTimeout = 15s
  commandTimeout = 15s
}

logging {
  levels {
    "ROOT" = "WARN"
    "ru.tinkoff.kora" = "INFO"
    "ru.tinkoff.kora.guide.cache" = "INFO"
  }
}
