httpServer {
  port = 8080
  system.port = 8085
  telemetry.logging.enabled = true
}

auth {
  apiKey {
    value = "MySecuredApiKey"
    value = ${?OPENAPI_HTTP_SERVER_ADVANCED_API_KEY}
  }
}

openapi {
  management {
    files = [ "openapi/user-http-server.yaml", "openapi/data-http-server.yaml" ]
    enabled = true
    endpoint = "/openapi"
    swaggerui {
      enabled = true
      endpoint = "/swagger-ui"
    }
  }
}

logging.levels {
  "root" = "WARN"
  "io.koraframework" = "INFO"
  "io.koraframework.guide.openapi.httpserver.advanced" = "INFO"
}

