httpServer {
  port = 8081
  system.port = 8086
  telemetry.logging.enabled = true
}

httpClient {
  // генератор 2.0 приводит первую букву имени API к строчной: @HttpClient("httpClient.usersApi")
  usersApi {
    url = "http://localhost:8080"
    url = ${?PUBLIC_API_URL}
    requestTimeout = 10s
  }
  telemetry.logging.enabled = true
}

logging {
  levels {
    "ROOT": "INFO"
    "io.koraframework": "INFO"
    "io.koraframework.guide.openapi.httpclient": "INFO"
  }
}


