grpcServer {
  port = 8092
  reflectionEnabled = true
  telemetry.logging.enabled = true
}

auth.apiKey.value = ${?GRPC_STREAMING_API_KEY}

logging {
  levels {
    "ROOT": "WARN"
    "ru.tinkoff.kora": "INFO"
    "ru.tinkoff.kora.guide.grpcserver.advanced": "INFO"
  }
}
