httpClient.petV2.petApi {
  url = ${HTTP_CLIENT_PET_V2_URL}
  requestTimeout = 10s
  getValuesConfig {
    requestTimeout = 20s
  }
  telemetry.logging.enabled = true
}

httpClient.petV3.petApi {
  url = ${HTTP_CLIENT_PET_V3_URL}
  requestTimeout = 10s
  getValuesConfig {
    requestTimeout = 20s
  }
  telemetry.logging.enabled = true
}

// секцию безопасности генератор читает по clientConfigPrefix, а не по securityConfigPrefix
httpClient.petV2 {
  apiKeyAuth = "MyAuthApiKey"
  basicAuth { username = "user", password = "pass" }
}

httpClient.petV3 {
  apiKeyAuth = "MyAuthApiKey"
  basicAuth { username = "user", password = "pass" }
}

logging.level {
  "root": "WARN"
  "io.koraframework": "INFO"
  "io.koraframework.example": "INFO"
}

