httpServer {
  port = 8081
  telemetry.logging.enabled = true
}

httpServer.system {
  port = 8086
  telemetry.logging.enabled = true
}


logging.levels {
  "root": "WARN"
  "io.koraframework": "DEBUG"
  "io.koraframework.example": "DEBUG"
}

httpServer.telemetry.logging.enabled = true