services:
  zeebe:
    image: camunda/zeebe:8.5.0
    environment:
      - ZEEBE_LOG_LEVEL=debug
    ports:
      - "26500:26500"
      - "9600:9600"
    volumes:
      - ./zeebe-application.yml:/usr/local/zeebe/config/application.yaml
