httpServer {
  publicApiHttpPort = 8080
  privateApiHttpPort = 8085
  telemetry.logging.enabled = true
}

kafka {
  producer {
    user-created {
      driverProperties {
        "bootstrap.servers": ${?KAFKA_BOOTSTRAP}
      }
      telemetry.logging.enabled = true
    }

    user-created-topic {
      topic = "user-created-events"
    }
  }

  consumer {
    user-created {
      topics = "user-created-events"
      pollTimeout = 250ms
      driverProperties {
        "bootstrap.servers": ${?KAFKA_BOOTSTRAP}
        "group.id": "guide-messaging-kafka-app"
        "auto.offset.reset" = "earliest"
        "enable.auto.commit" = true
      }
      telemetry.logging.enabled = true
    }
  }
}

logging.level {
  "ROOT" = "INFO"
  "ru.tinkoff.kora" = "INFO"
  "ru.tinkoff.kora.guide.messaging.kafka" = "INFO"
}
