httpServer {
  publicApiHttpPort = 8080
  privateApiHttpPort = 8085
  telemetry.logging.enabled = true
}

s3client {
  url = ${S3_URL}
  accessKey = ${S3_ACCESS_KEY}
  secretKey = ${S3_SECRET_KEY}
  region = "us-east-1"
  region = ${?S3_REGION}

  uploads {
    bucket = "uploads"
    bucket = ${?S3_BUCKET}
  }
}

logging {
  levels {
    "ROOT": "WARN"
    "ru.tinkoff.kora": "INFO"
  }
}