kafka {
  producer {
    my-topic {
      topic: "my-topic-producer"
    }
    my-publisher {
      driverProperties {
        "bootstrap.servers": ${KAFKA_BOOTSTRAP}
      }
      telemetry.logging.enabled = true
    }
    my-transactional {
      idPrefix: "my-transaction"
      maxPoolSize: 10
      telemetry.logging.enabled = true
    }
  }
  consumer {
    my-listener {
      pollTimeout: 250ms
      topics: "my-topic-consumer"
      driverProperties {
        "bootstrap.servers": ${KAFKA_BOOTSTRAP}
        "group.id": "my-group-id"
        "auto.offset.reset" = "earliest"
        "enable.auto.commit" = true
      }
      telemetry.logging.enabled = true
    }
    skip-listener {
      pollTimeout: 100ms
      topics: "skip-topic"
      driverProperties {
        "bootstrap.servers": ${KAFKA_BOOTSTRAP}
        "group.id": "skip-example-kotlin"
        "auto.offset.reset" = "earliest"
        "enable.auto.commit" = true
      }
    }
    malformed-listener {
      pollTimeout: 100ms
      topics: "malformed-topic"
      driverProperties {
        "bootstrap.servers": ${KAFKA_BOOTSTRAP}
        "group.id": "malformed-example-kotlin"
        "auto.offset.reset" = "earliest"
        "enable.auto.commit" = true
      }
    }
    retry-listener {
      pollTimeout: 100ms
      topics: "retry-topic"
      driverProperties {
        "bootstrap.servers": ${KAFKA_BOOTSTRAP}
        "group.id": "retry-example-kotlin"
        "auto.offset.reset" = "earliest"
        "enable.auto.commit" = true
      }
    }
    transactional-pipeline {
      pollTimeout: 100ms
      topics: "transactional-input"
      driverProperties {
        "bootstrap.servers": ${KAFKA_BOOTSTRAP}
        "group.id": "transactional-pipeline-example-kotlin"
        "auto.offset.reset" = "earliest"
        "enable.auto.commit" = false
        "isolation.level" = "read_committed"
      }
    }
  }
}

resilient.retry.kafka-listener {
  delay = 10ms
  attempts = 3
}


logging.levels {
  "root": "WARN"
  "io.koraframework": "INFO"
  "io.koraframework.example": "INFO"
}
