services:
  postgres:
    image: postgres:16.4-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres


  application:
    image: kora-java-camunda-engine
    restart: unless-stopped
    ports:
      - '8080:8080'
      - '8085:8085'
      - '8090:8090'
    environment:
      POSTGRES_JDBC_URL: jdbc:postgresql://postgres:5432/postgres
      POSTGRES_USER: postgres
      POSTGRES_PASS: postgres
    depends_on:
      - postgres
