services:
  zeebe-broker:
    image: camunda/zeebe:8.6.7
    ports:
      - "26500:26500"
      - "9600:9600"
      - "8060:8080"
    environment:
      - ZEEBE_LOG_LEVEL=INFO
      - ZEEBE_BROKER_DATA_DISKUSAGECOMMANDWATERMARK=0.998
      - ZEEBE_BROKER_DATA_DISKUSAGEREPLICATIONWATERMARK=0.999
      - "JAVA_TOOL_OPTIONS=-Xms512m -Xmx512m"
