zeebe.client {
  initializationFailTimeout = "10s"
  grpc.url = ${ZEEBE_GRPC_URL}
  rest.url = ${ZEEBE_REST_URL}
  deployment.resources = "classpath:bpm"

  telemetry.logging.enabled = true
}


logging.levels {
  "root": "WARN"
  "io.koraframework": "DEBUG"
  "io.koraframework.example": "DEBUG"
}
