httpServer {
  port = 8080
  system.port = 8085
  telemetry.logging.enabled = true
}

auth {
  apiKey {
    value = "MySecuredApiKey"
    value = ${?HTTP_ADVANCED_API_KEY}
  }
}

logging {
  levels {
    "ROOT": "WARN"
    "io.koraframework": "INFO"
  }
}
