foo:
  valueEnvRequired: ${ENV_VALUE_REQUIRED}
  valueEnvOptional: ${?ENV_VALUE_OPTIONAL}
  valueEnvDefault: ${ENV_VALUE_DEFAULT:someDefaultValue}
#  valueEnvDefault: "someDefaultValue"
  valueString: "SomeString"
  valueRef: ${foo.valueString}Other${foo.valueString}
  valueUuid: "20684ccb-81f8-4fac-8ec0-297b08ff993d"
  valuePattern: ".*somePattern.*"
  valueEnum: "ANY"
  valueLocalDate: "2020-10-10"
  valueLocalTime: "12:10:10"
  valueLocalDateTime: "2020-10-10T12:10:10"
  valueOffsetTime: "12:10:10+03:00"
  valueOffsetDateTime: "2020-10-10T12:10:10+03:00"
  valuePeriodAsInt: 1
  valuePeriodAsString: "1d"
  valueDuration: "250s"
  valueInt: 1
  valueLong: 2
  valueBigInt: 3
  valueDouble: 4.1
  valueBigDecimal: 5.1
  valueBoolean: true
  valueListAsString: "v1,v2"
  valueListAsArray: ["v1", "v2"]
  valueSetAsString: "v1,v2"
  valueSetAsArray: ["v1", "v2"]
  valueMap:
    k1: "v1"
    k2: "v2"
  valueProperties:
    k1: "v1"
    k2: "v2"
  bar:
    someBarString: "someString"
    baz:
      someBazString: "someString"
