httpServer {
  port = 8080
  system.port = 8085
  telemetry.logging.enabled = true
}

jdbc {
  jdbcUrl = ${?POSTGRES_JDBC_URL}
  username = ${?POSTGRES_USER}
  password = ${?POSTGRES_PASS}
  maxPoolSize = 10
  poolName = "guide-jdbc"
}

flyway {
  locations = "db/migration"
}

logging {
  levels {
    "ROOT": "WARN"
    "io.koraframework": "INFO"
  }
}
