httpServer {
  publicApiHttpPort = 8080
  privateApiHttpPort = 8085
  telemetry.logging.enabled = true
}

resilient {
  retry {
    default {
      delay = 20ms
      attempts = 3
      delayStep = 20ms
    }
  }
  timeout {
    default {
      duration = 100ms
    }
  }
  circuitbreaker {
    default {
      slidingWindowSize = 2
      minimumRequiredCalls = 2
      failureRateThreshold = 100
      permittedCallsInHalfOpenState = 1
      waitDurationInOpenState = 200ms
      failurePredicateName = "RecordServerErrorsOnly"
    }
  }
}

logging {
  levels {
    "ROOT": "WARN"
    "ru.tinkoff.kora": "INFO"
  }
}
