httpServer {
  publicApiHttpPort = 8081
  privateApiHttpPort = 8086
  telemetry.logging.enabled = true
}

auth.apiKey.value = "test-api-key"
auth.apiKey.value = ${?GRPC_STREAMING_API_KEY}

grpcClient {
  UserStreamingService {
    url = "http://localhost:8092"
    url = ${?GRPC_STREAMING_SERVER_URL}
    telemetry.logging.enabled = true
  }
}

logging {
  levels {
    "ROOT": "INFO"
    "ru.tinkoff.kora": "INFO"
    "ru.tinkoff.kora.guide.grpcclient.advanced": "INFO"
  }
}
