httpServer {
  publicApiHttpPort = 8081
  privateApiHttpPort = 8086
  telemetry.logging.enabled = true
}

grpcClient {
  UserService {
    url = "http://localhost:8090"
    url = ${?GRPC_SERVER_URL}
    telemetry.logging.enabled = true
  }
}

logging {
  levels {
    "ROOT": "INFO"
    "ru.tinkoff.kora": "INFO"
    "ru.tinkoff.kora.guide.grpcclient": "INFO"
  }
}
