httpServer {
  port = 8080
  system.port = 8085
  telemetry.logging.enabled = true
}

jdbc {
  jdbcUrl = ${POSTGRES_JDBC_URL}
  username = ${POSTGRES_USER}
  password = ${POSTGRES_PASS}
  maxPoolSize = 10
  poolName = "petclinic"
  initializationFailTimeout = 10s
  telemetry.logging.enabled = true
}

flyway.locations = "db/migration"

logging.levels {
  "root" = "WARN"
  "io.koraframework" = "INFO"
  "io.koraframework.example.petclinic" = "INFO"
}
