kafka:
  publisher:
    task:
      topic: "tasks"
      driverProperties:
        bootstrap:
          servers: ${KAFKA_BOOTSTRAP}
      telemetry.logging.enabled: true
  listener:
    user:
      pollTimeout: 250ms
      topics: "users"
      driverProperties:
        bootstrap.servers: ${KAFKA_BOOTSTRAP}
        group.id: "users-gi"
        auto.offset.reset: "latest"
        enable.auto.commit: true
      telemetry.logging.enabled: true


logging:
  level:
    root: "WARN"
    ru.tinkoff.kora: "INFO"
    ru.tinkoff.kora.example: "INFO"
    ru.tinkoff.kora.application.graph.internal.loom.VirtualThreadExecutorHolder: "DEBUG"