httpServer {
  publicApiHttpPort = 8080
  privateApiHttpPort = 8085
  telemetry.logging.enabled = true
}

auth {
  apiKey {
    value = "MySecuredApiKey"
    value = ${?OPENAPI_HTTP_SERVER_ADVANCED_API_KEY}
  }
}

openapi {
  management {
    file = [ "openapi/user-http-server.yaml", "openapi/data-http-server.yaml" ]
    enabled = true
    endpoint = "/openapi"
    swaggerui {
      enabled = true
      endpoint = "/swagger-ui"
    }
  }
}

logging.level {
  "root" = "WARN"
  "ru.tinkoff.kora" = "INFO"
  "ru.tinkoff.kora.guide.openapi.httpserver.advanced" = "INFO"
}

