httpServer {
  publicApiHttpPort = 8080
  privateApiHttpPort = 8085
  telemetry.logging.enabled = true
}


logging.level {
  "root": "WARN"
  "root": ${?LOGGING_LEVEL_ALL}
  "root": ${?LOGGING_LEVEL_ROOT}

  "ru.tinkoff.kora": "INFO"
  "ru.tinkoff.kora": ${?LOGGING_LEVEL_ALL}
  "ru.tinkoff.kora": ${?LOGGING_LEVEL_KORA}
  "ru.tinkoff.kora.http": ${?LOGGING_LEVEL_ALL}
  "ru.tinkoff.kora.http": ${?LOGGING_LEVEL_KORA_HTTP}

  "ru.tinkoff.kora.example": "INFO"
  "ru.tinkoff.kora.example": ${?LOGGING_LEVEL_ALL}
  "ru.tinkoff.kora.example": ${?LOGGING_LEVEL_APP}
}
