httpServer {
  port = 8090
  telemetry.logging.enabled = true
}

httpServer.system {
  port = 8095
  telemetry.logging.enabled = true
}


jdbc {
  jdbcUrl = ${POSTGRES_JDBC_URL}
  username = ${POSTGRES_USER}
  password = ${POSTGRES_PASS}
  maxPoolSize = 10
  poolName = "kora"
  initializationFailTimeout = "10s"
  telemetry.logging.enabled = true
}


pet-cache {
  maximumSize = 1000
  maximumSize = ${?CACHE_MAX_SIZE}
  expireAfterWrite = ${?CACHE_EXPIRE_WRITE}
}


openapi {
  management {
    enabled = true
    files = "openapi/http-server.yaml"
    swaggerui {
      enabled = true
    }
    scalar {
      enabled = true
    }
  }
}


resilient {
  circuitbreaker.pet {
    countBased.windowSize = 50
    minimumRequiredCalls = 25
    failureRateThreshold = 50
    waitDurationInOpenState = "25s"
    permittedCallsInHalfOpenState = 10
  }
  timeout.pet {
    duration = "5000ms"
  }
  retry.pet {
    delay = "500ms"
    delayStep = "5s"
    attempts = 3
    attempts = ${?RETRY_ATTEMPTS}
  }
}


logging.level {
  "root": "WARN"
  "root": ${?LOGGING_LEVEL_ALL}
  "root": ${?LOGGING_LEVEL_ROOT}

  "io.koraframework": "INFO"
  "io.koraframework": ${?LOGGING_LEVEL_ALL}
  "io.koraframework": ${?LOGGING_LEVEL_KORA}
  "io.koraframework.http.server": ${?LOGGING_LEVEL_ALL}
  "io.koraframework.http.server": ${?LOGGING_LEVEL_KORA_HTTP_SERVER}
  "io.koraframework.database": ${?LOGGING_LEVEL_ALL}
  "io.koraframework.database": ${?LOGGING_LEVEL_KORA_DATABASE}
  "io.koraframework.cache": ${?LOGGING_LEVEL_ALL}
  "io.koraframework.cache": ${?LOGGING_LEVEL_KORA_CACHE}
  "io.koraframework.resilient": ${?LOGGING_LEVEL_ALL}
  "io.koraframework.resilient": ${?LOGGING_LEVEL_KORA_RESILIENT}

  "io.koraframework.example": "INFO"
  "io.koraframework.example": ${?LOGGING_LEVEL_ALL}
  "io.koraframework.example": ${?LOGGING_LEVEL_APP}
}
