name: Test PR

on:
  pull_request:
    branches:
      - "master"


permissions:
  contents: read
  checks: write
  pull-requests: write


jobs:
  build-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ "17" ]
        task: [ "database", "client", "server", "graalvm", "other" ]
    name: Pull Request Java ${{ matrix.java }} for ${{ matrix.task }}
    steps:
      - uses: actions/checkout@v4
      - name: JDK setup
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: "adopt"

      - name: Gradle setup
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' }}
          gradle-home-cache-cleanup: ${{ github.ref == 'refs/heads/master' }}

      - name: Gradle classes
        run: "./gradlew classes-${{ matrix.task }} --scan"

      - name: Gradle tests classes
        run: "./gradlew testClasses-${{ matrix.task }} --scan"

      - name: Gradle tests
        run: "./gradlew test-${{ matrix.task }} jacocoTestReport --no-parallel --scan"

      - name: Report tests
        if: ${{ matrix.java }} == "17"
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: |
            **/test-results/**/*.xml
