name: Build Master

on:
  push:
    branches:
      - "master"

jobs:
  build-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ "21" ]
        type: [ "Examples" ]
        lang: [ "Java", "Kotlin" ]
        feature: [ "Database", "Client", "Server", "Graalvm", "Other" ]
    name: Pull Request Java ${{ matrix.java }} for ${{ matrix.type }}-${{ matrix.lang }}-${{ matrix.feature }}
    env:
      GRADLE_TASK_SUFFIX: ${{ matrix.type }}${{ matrix.lang }}${{ matrix.feature }}
    steps:
      - uses: actions/checkout@v4
      - name: JDK setup
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: "adopt"

      - name: Gradle setup
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' }}
          gradle-home-cache-cleanup: ${{ github.ref == 'refs/heads/master' }}

      - name: Gradle build classes
        run: "./gradlew classes${GRADLE_TASK_SUFFIX} --no-daemon --no-parallel --scan --stacktrace"

      - name: Gradle build test classes
        run: "./gradlew testClasses${GRADLE_TASK_SUFFIX} --no-daemon --no-parallel --scan --stacktrace"

      - name: Gradle run tests
        run: "./gradlew test${GRADLE_TASK_SUFFIX} jacocoTestReport --no-daemon --no-parallel --scan --stacktrace"
