name: Test PR

on:
  pull_request:
    branches:
      - "master"


permissions:
  contents: read
  checks: write
  pull-requests: write


jobs:
  build-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ "17" ]
        task: [ "database", "client", "server", "graalvm", "other" ]
    name: Pull Request Java ${{ matrix.java }} for ${{ matrix.task }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: "adopt"

      - name: Build classes
        run: "./gradlew classes-${{ matrix.task }}"

      - name: Build tests
        run: "./gradlew testClasses-${{ matrix.task }}"

      - name: Run tests
        run: "./gradlew test-${{ matrix.task }} jacocoTestReport --no-parallel"

      - name: Report tests
        if: ${{ matrix.java }} == "17"
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: |
            **/test-results/**/*.xml
