name: Build Master

on:
  push:
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [ "database", "client", "server", "graalvm", "kotlin", "other" ]
    name: Running tests for ${{ matrix.task }}
    steps:
      - uses: actions/checkout@v4
      - name: JDK setup
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Gradle setup
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' }}
          gradle-home-cache-cleanup: ${{ github.ref == 'refs/heads/master' }}

      - name: Gradle classes
        run: "./gradlew classes-${{ matrix.task }} --scan"

      - name: Gradle tests classes
        run: "./gradlew testClasses-${{ matrix.task }} --scan"

      - name: Gradle tests
        run: "./gradlew test-${{ matrix.task }} jacocoTestReport --no-parallel --scan"
