services:
  zeebe:
    image: camunda/zeebe:8.6.7
    ports:
      - "26500:26500"
      - "9600:9600"
      - "8060:8080"
    environment:
      - ZEEBE_LOG_LEVEL=WARN
      - ZEEBE_BROKER_DATA_DISKUSAGECOMMANDWATERMARK=0.998
      - ZEEBE_BROKER_DATA_DISKUSAGEREPLICATIONWATERMARK=0.999
      - "JAVA_TOOL_OPTIONS=-Xms512m -Xmx512m"


  application:
    image: kora-java-camunda-zeebe-worker
    build: .
    restart: unless-stopped
    ports:
      - '8085:8085'
    environment:
      ZEEBE_GRPC_URL: http://zeebe:26500
    depends_on:
      - zeebe
