httpServer {
  publicApiHttpPort = 8081
  privateApiHttpPort = 8086
  telemetry.logging.enabled = true
}

httpClient {
  userApi {
    url = "http://localhost:8080"
    url = ${?USER_API_URL}
    requestTimeout = 10s
  }
  telemetry.logging.enabled = true
}

logging {
  levels {
    "ROOT": "INFO"
    "ru.tinkoff.kora": "INFO"
  }
}

